dependencies:
  - any: ["uv.lock"]
    all: ["!**/*.py"]

documentation:
  - any: ["**/*.md"]
    all: ["!**/*.py", "!.github/**/*"]

github structure:
  - any: [".github/**/*"]
    all: ["!**/*.py"]

testing:
  - any: ["tests/**"]
    all: ["!cgt_calc/**"]
