name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "performance"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "📔 Documentation"
    labels:
      - "documentation"
  - title: "🏅 Code Quality Improvements"
    labels:
      - "code quality"
  - title: "🧱 Dependency Updates"
    labels:
      - "dependencies"
  - title: "🔧 Maintenance"
    labels:
      - "github structure"
      - "removal"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "feature"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
