name: "Common steps to install and cache dependencies"

inputs:
  python-version:
    description: "Python version to set up"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies with uv
      shell: bash
      run: uv sync
