name: Autolabel pull requests

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read
  pull-requests: write

jobs:
  autolabel:
    name: Autolabeler
    runs-on: ubuntu-latest
    steps:
      - name: Run release-drafter autolabeler
        uses: release-drafter/release-drafter@v7.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
