name: Labeler

on:
  pull_request_target:
    branches:
      - main

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-latest
    steps:
      - name: Run Pull Request Labeler
        uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
